import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { AppLayout } from './AppLayout'
import { api } from '../lib/api'

export function ProjectMembersPage({ user }) {
  const { projectId } = useParams()
  const [members, setMembers] = useState([]); const [error, setError] = useState(''); const [form, setForm] = useState({ email: '', role: 'member' }); const [message, setMessage] = useState('')
  const load = () => api(`/projects/${projectId}/members`).then(setMembers).catch((err) => setError(err.message))
  useEffect(() => { api(`/projects/${projectId}/members`).then(setMembers).catch((err) => setError(err.message)) }, [projectId])
  const myRole = members.find((member) => member.user._id === user._id)?.role
  const isAdmin = myRole === 'admin'
  const changeRole = async (member, newRole) => { try { await api(`/projects/${projectId}/members/${member.user._id}`, { method: 'PUT', body: JSON.stringify({ newRole }) }); load() } catch (err) { setError(err.message) } }
  const remove = async (member) => { if (!window.confirm(`Remove ${member.user.fullName || member.user.username} from this project?`)) return; try { await api(`/projects/${projectId}/members/${member.user._id}`, { method: 'DELETE' }); load() } catch (err) { setError(err.message) } }
  const addMember = async (event) => { event.preventDefault(); setError(''); try { await api(`/projects/${projectId}/members`, { method: 'POST', body: JSON.stringify(form) }); setMessage('Member added.'); setForm({ email: '', role: 'member' }); load() } catch (err) { setError(err.message) } }
  return <AppLayout user={user}><Link to={`/projects/${projectId}/tasks`} className="text-sm text-indigo-600">← Back to project board</Link><h2 className="mt-3 text-2xl font-bold">Project members</h2>{isAdmin && <><div className="mt-4 flex flex-wrap gap-3"><span className="rounded-lg bg-indigo-50 px-3 py-2 text-sm font-semibold text-indigo-700">Add existing member</span><Link to={`/projects/${projectId}/invite`} className="rounded-lg border border-indigo-100 bg-white px-3 py-2 text-sm font-semibold text-indigo-700">Invite new user</Link></div><form onSubmit={addMember} className="mt-4 max-w-md rounded-xl border border-indigo-100 bg-blue-50/60 p-5"><h3 className="font-semibold">Add existing Orbit user</h3><label className="mt-3 block text-sm">Email<input required type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} className="mt-1 w-full rounded-lg border border-slate-300 bg-white p-3" /></label><label className="mt-3 block text-sm">Role<select value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value })} className="mt-1 w-full rounded-lg border border-slate-300 bg-white p-3"><option value="member">Member</option><option value="project_admin">Project admin</option></select></label><button className="mt-4 rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white">Add member</button>{message && <p className="mt-3 text-sm text-emerald-700">{message}</p>}</form></>}<section className="mt-6 max-w-2xl space-y-3">{members.map((member) => <article key={member.user._id} className="flex items-center justify-between gap-4 rounded-xl border border-indigo-100 bg-white p-4 shadow-sm"><div><p className="font-medium">{member.user.fullName || member.user.username}</p><p className="text-xs text-slate-500">@{member.user.username}</p></div>{isAdmin ? <div className="flex items-center gap-2"><select value={member.role} onChange={(e) => changeRole(member, e.target.value)} className="rounded-lg border border-slate-300 bg-white p-2 text-sm"><option value="admin">Admin</option><option value="project_admin">Project admin</option><option value="member">Member</option></select>{member.user._id !== user._id && <button onClick={() => remove(member)} className="text-sm text-red-600">Remove</button>}</div> : <span className="rounded-lg bg-indigo-100 px-2 py-1 text-xs text-indigo-700">{member.role}</span>}</article>)}{!members.length && <p className="text-slate-600">No members found.</p>}</section>{error && <p className="mt-4 text-red-700">{error}</p>}</AppLayout>
}
