import { useCallback, useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { AppLayout } from "./AppLayout";
import { api } from "../lib/api";

export function ProjectBriefPage({ user }) {
  const { projectId } = useParams(); const [project, setProject] = useState(null); const [role, setRole] = useState(""); const [file, setFile] = useState(null); const [error, setError] = useState(""); const [uploading, setUploading] = useState(false); const [editingDescription, setEditingDescription] = useState(false); const [description, setDescription] = useState("");
  const load = useCallback(() => api(`/projects/${projectId}`).then((data) => { setProject(data); setRole(data.role || ""); }).catch((err) => setError(err.message)), [projectId]);
  useEffect(() => { load(); }, [load]);
  const upload = async (event) => { event.preventDefault(); if (!file) return; if (file.size > 5 * 1000 * 1000) { setError("Project Brief must be 5 MB or smaller"); return; } setUploading(true); setError(""); try { const formData = new FormData(); formData.append("brief", file); await api(`/projects/${projectId}/brief`, { method: "PUT", body: formData }); setFile(null); load(); } catch (err) { setError(err.message); } finally { setUploading(false); } };
  const openBrief = async (event) => { event.preventDefault(); const briefWindow = window.open("", "_blank"); setError(""); try { const freshProject = await api(`/projects/${projectId}?includeBriefUrl=true`); if (!freshProject.brief?.url) throw new Error("Project Brief is no longer available"); if (briefWindow) briefWindow.location.assign(freshProject.brief.url); else window.location.assign(freshProject.brief.url); } catch (err) { briefWindow?.close(); setError(err.message); } };
  const saveDescription = async (event) => { event.preventDefault(); await api(`/projects/${projectId}`, { method: "PUT", body: JSON.stringify({ description }) }); setEditingDescription(false); load(); };
  const canUpload = ["admin", "project_admin"].includes(role);
  return <AppLayout user={user}><Link to={`/projects/${projectId}/tasks`}>← Back to My Workload</Link><h2 className="mt-4 text-3xl font-semibold">Project Brief</h2>{error && <p className="mt-4 text-red-700">{error}</p>}{project && <p className="mt-3 text-slate-600">{project.description || "No project description."}</p>}{project && (project.brief?.key ? <a className="mt-6 inline-flex rounded-xl border border-indigo-200 bg-indigo-50 px-5 py-3 font-semibold text-indigo-700" href="#open-brief" onClick={openBrief} target="_blank" rel="noreferrer">Open {project.brief.name || "Project Brief"}</a> : <p className="mt-6 text-slate-500">No Project Brief has been added yet.</p>)}{canUpload && <section className="mt-6 max-w-lg"><button onClick={() => { if (!editingDescription) setDescription(project?.description || ""); setEditingDescription((current) => !current); }} className="rounded-lg border border-slate-200 bg-white px-4 py-2 text-sm font-semibold text-slate-700">Update Description</button>{editingDescription && <form onSubmit={saveDescription} className="mt-3"><textarea value={description} onChange={(event) => setDescription(event.target.value)} className="min-h-24 w-full rounded-lg border border-slate-200 p-3" /><button className="mt-2 rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white">Save Description</button></form>}<form onSubmit={upload} className="mt-4 rounded-xl border border-slate-200 bg-white/70 p-4"><p className="font-semibold">{project?.brief ? "Update Project Brief" : "Upload Project Brief"}</p><input required type="file" accept=".pdf,.docx" onChange={(event) => setFile(event.target.files?.[0] || null)} className="mt-3 block w-full text-sm" /><button disabled={uploading} className="mt-4 rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-60">{uploading ? "Uploading…" : project?.brief ? "Update Project Brief" : "Upload Project Brief"}</button></form></section>}</AppLayout>;
}
