from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT, WD_CELL_VERTICAL_ALIGNMENT
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.enum.section import WD_SECTION
from pathlib import Path

OUT = Path('/Users/purukumar/Desktop/RESUME INCOMING /TaskForce_Orbit_Complete_Placement_Handbook.docx')
BLUE='2E74B5'; NAVY='17365D'; INK='16283E'; PALE='EDF3F8'; GOLD='7A5A00'

topics = [
('How to use this handbook','Treat this as an interview map, not a script. Learn the short answer first, then practise the follow-up route: problem, decision, implementation, evidence, limitation, next step.','Start with the 60-second pitch. For every technology, be able to say what it is, where it exists in Task Force Orbit, why it fits, and one honest limitation.','Interviewers reward ownership and clear reasoning more than a long list of tools. Do not memorise claims you cannot demonstrate.'),
('The 60-second project pitch','Task Force Orbit is a full-stack collaborative project-management workspace. It supports secure onboarding, projects and role-based teams, tasks, review workflow, notifications, file attachments, project briefs, and a personal Softboard.','Say: “I built it to make project coordination visible: members submit work, project admins review it, and each role sees the right actions. I owned the React UI, Express API, MongoDB data layer, secure authentication, S3 file flow and Vercel deployment.”','Lead with the user problem and architecture; do not begin by listing libraries.'),
('The two-minute demo story','A credible demo follows a user journey: register, verify email, create project, invite member, assign task, submit work, review it, notify the member, then show a personal Softboard.','Explain that the project creator is kept as Admin. A member’s work goes to In Review; an admin can approve to Completed or return it to In Progress.','Mention both happy path and safeguards. An interviewer will often ask what happens when upload, email, or permission fails.'),
('Product problem and users','The product serves individual contributors who need actionable work, and project leaders who need visibility without losing control of review. Softboard is deliberately personal, while projects are collaborative.','Users are Admin, Project Admin and Member. Role checks are enforced server-side through project membership, not only hidden UI buttons.','A thoughtful scope is better than pretending to be Jira. Explain that this is a placement-grade product with intentionally bounded collaboration features.'),
('System architecture','The browser uses React/Vite and calls an Express REST API. Express applies middleware, authentication and permission checks, then controllers use Mongoose to access MongoDB. Private files live in S3 and are read through short-lived signed URLs.','Trace one request: React API helper attaches an in-memory bearer token; Express verifies it; permission middleware loads membership; controller validates input; MongoDB writes data; JSON response updates UI.','This separation keeps UI, rules and persistence independently testable. A monolith is acceptable here because deployment and team size are small.'),
('React and Vite','React is the component-based UI layer. Vite gives a fast development server and production build pipeline without adding a full server-rendering framework.','Use React state for form/modal/task interactions, React Router for routes, and a shared API helper for authenticated requests.','Why not Next.js? Server rendering and SEO are valuable for content sites; this authenticated dashboard benefits more from a focused SPA and simpler deployment.'),
('Client routing and protected screens','React Router separates login, dashboard, project routes, notifications and Softboard. Protected views must redirect unauthenticated users, but that is convenience, not security.','The API remains the authority. A user who manually calls an endpoint cannot bypass verifyJWT or project role middleware simply because a front-end button is visible.','Say “defence in depth”: UI guards reduce confusion; backend authorization protects data.'),
('Forms, validation and feedback','Forms provide immediate feedback, but the API validates again because browser input is untrusted. The project creation modal keeps errors inside the modal so the user is not stranded after a duplicate-name failure.','Registration handles an existing unverified account by updating the pending record and sending a fresh verification email instead of returning a confusing permanent duplicate error.','Explain client validation as usability and server validation as security/correctness. Never claim client validation is sufficient.'),
('Express application pipeline','Express middleware is ordered: parsing limits, cookies, CORS/origin controls, security headers, rate limiting, route middleware, controllers, and central error handling.','The app limits JSON/urlencoded payloads to 16 KB; uploads use dedicated multipart handling. Controllers return consistent ApiResponse/ApiError shapes.','Middleware centralizes cross-cutting rules. Putting every check in every controller would duplicate logic and produce inconsistent behaviour.'),
('REST API design','The API models resources such as users, projects, tasks, notes, notifications and softboard notes. HTTP methods communicate intent; status codes and structured errors let the client respond predictably.','Use request validation and matched sanitized data before persistence. Validate Mongo ObjectIds instead of allowing malformed IDs to reach queries.','REST was chosen because the dashboard has clear resources and request/response interactions. GraphQL would add flexibility but also schema and caching complexity.'),
('MongoDB and Mongoose','MongoDB stores the operational data as documents; Mongoose defines schemas, validation, hooks and model access. It fits rapidly evolving product objects such as tasks with attachments, submissions and activity.','Project membership, task fields, notifications, softboard notes and project briefs are modeled as collections/documents. References are used where entities have independent lifecycles.','Why not PostgreSQL? A relational database is excellent for strict joins and reporting. MongoDB made iterative nested data and document-shaped API responses faster for this project.'),
('Data modeling: embed versus reference','Embed small, owned data that is read with the parent; reference entities that grow independently or are reused. This is a deliberate MongoDB design decision, not a rule that one approach always wins.','Files are represented by metadata/key, not binary content in MongoDB. Users, projects, memberships and tasks are independently addressed records.','Be ready to discuss query patterns first. MongoDB documentation frames embed/reference selection around access patterns and data lifecycle.'),
('Indexes and duplicate-name bug','A unique index protects a project name where the schema requires uniqueness. The duplicate-key error occurred because the database correctly rejected a repeated value, but the UI originally did not present the error well.','The fix was not to remove the constraint. It was to catch the database error, return a meaningful response, and show it inside the creation modal.','A database constraint is the final integrity layer. Application pre-checks improve messages but cannot eliminate races between concurrent requests.'),
('JWT fundamentals','A JSON Web Token is a signed compact credential containing claims. The signature lets the server detect tampering; it does not encrypt the payload.','Task Force Orbit signs access tokens with user id, email and username. API requests send them as Bearer tokens. The server verifies signature/expiry before attaching the user to the request.','Do not say JWT “stores a session in the database.” Here it is a stateless access credential, while refresh-token state is stored on the user record.'),
('Access token and refresh token flow','Access tokens are held only in front-end memory. On expiry, the client makes one refresh call; the httpOnly refresh cookie is sent automatically, the API verifies/rotates it, then the request retries once.','Refresh tokens are persisted against the user and cookie settings include httpOnly, production secure flag, sameSite none in production, scoped auth path and ten-day max age.','This limits exposure versus localStorage. The trade-off is that a page refresh needs a refresh call to restore access state.'),
('Cookies, CORS and CSRF','CORS controls which browser origins can read API responses; it is not authentication. Cookies need SameSite/Secure/httpOnly choices, and state-changing requests need origin checks/CSRF thinking.','The API uses configured allowed origins, credentials-aware CORS and an origin-check middleware for unsafe methods. The bearer access token is separate from the refresh cookie.','If asked about CSRF, say same-site policy and origin validation reduce risk, but you would reassess if the authentication model or allowed origins change.'),
('Password storage and account recovery','Passwords are never stored in readable form. A Mongoose pre-save hook hashes with bcrypt (cost factor 10). Password-reset and verification flows use random tokens; only a SHA-256 hash plus expiry is stored.','The raw token goes only in the email link. Expired or used values fail verification. This limits impact if database data is exposed.','bcrypt is intentionally slow to resist password guessing. Argon2 is a valid modern alternative; the important property is adaptive password hashing, not brand loyalty.'),
('Email verification and Mailtrap','Email verification prevents an address from becoming a usable account until it proves control of the mailbox. SMTP delivery can fail or be rate-limited, so pending accounts need a recovery path.','Mailtrap is used as the SMTP provider/configuration for verification, reset and invite mails. Re-registration refreshes an unverified record and sends another link.','Do not promise email is synchronous. The API handles provider failures clearly; production maturity would add delivery logs, retries and a transactional provider plan.'),
('Role-based access control','RBAC maps permissions to roles. In this project: Admin has project authority, Project Admin reviews/workflows, and Member performs assigned work. Exact business checks live in middleware/controllers.','validateProjectPermission reads membership and role before protected project actions. Creator remains Admin; the last admin cannot be removed or demoted.','Roles are not merely labels in the UI. The backend repeats the authorization decision for every sensitive endpoint.'),
('Task status state machine','A task has To Do, In Progress, In Review and Completed states. The review state is meaningful: it represents submitted work awaiting project-admin decision, not an accidental return to To Do.','Member submission routes to In Review. Admin approves to Completed or requests changes to In Progress. Review handling avoids the earlier invalid To Do transition.','Use the phrase “finite state machine” carefully: it is a controlled transition model, even if implemented with validation logic rather than a separate state-machine library.'),
('Task submission and attachments','A member can add a comment and a single constrained attachment, then submit for review. The project admin receives the submission context and task status update.','Task attachments are limited to 1 MB and selected types. Multer receives multipart data in memory; validation happens before upload.','Limits are not cosmetic. They control cost, latency and abuse. For larger workloads, use direct-to-S3 multipart upload with server-issued constraints.'),
('AWS S3 private file strategy','S3 stores files; MongoDB stores only object key, original name, MIME type and size. Objects are private. Download access is created with a temporary signed GET URL (about five minutes).','This avoids making project documents public and avoids putting large binary blobs in the database. The server decides whether a user may obtain a signed URL.','S3 is pay-as-you-go. Explain cost hygiene: file limits, private bucket, lifecycle rules, minimal uploads, and never expose AWS credentials in the front end.'),
('Project brief feature','A Project Brief is a shared project-level PDF/DOCX that an admin can upload during creation or later. It helps a newly invited member understand scope without relying on chat.','Brief uploads have a separate 5 MB cap and approved document types. Members can view/download only through normal project access.','Call it a lightweight onboarding artifact. A full document-management system is deliberately out of scope.'),
('Notifications and activity','Notifications represent user-facing events and read/unread state; activity gives project context. A project admin can send a task reminder to the assigned member.','Notification records persist in MongoDB rather than only a browser toast, so they survive sessions and appear on the Notifications route.','This is polling-based/normal REST refresh, not real-time push. WebSockets would be the next step if immediate multi-user presence became a hard requirement.'),
('Five-minute refresh and freshness','The dashboard can refetch data every five minutes (300,000 ms), reducing stale data without forcing a manual reload.','A reusable useBackgroundRefresh hook silently reloads notifications, dashboard projects and the active task board. It does not reload the browser or form state; it pauses when the tab is hidden and refreshes once when the user returns. Explicit post-mutation refresh remains immediate.','Polling is intentionally simple and predictable for a placement project with moderate traffic. Explain trade-off: it consumes periodic requests; SSE/WebSockets are better for near-real-time updates but add persistent connection and scaling complexity.'),
('Softboard product scope','Softboard is personal—not project-specific—so it does not mix private planning with team tasks. It uses note titles, checklist items, muted paper colors and a corkboard visual language.','SoftboardNote data is owned by one user. New users receive five professional default notes, and the feature limits the board to nine notes.','This feature demonstrates product thinking and interaction design. Do not oversell it as a team collaboration board.'),
('Softboard performance: slot grid','Free pixel dragging was replaced by fixed slot indices 0–8. The user drags toward a hook, then the note snaps to the closest available slot rather than persisting raw x/y positions.','The UI updates optimistically at drop time; writes are serialized in a promise chain so slow API responses do not revert later moves. CSS transform/short transition keeps motion responsive.','This trades unlimited positioning for stable responsive interaction and small data. It is an example of choosing a constraint to improve performance.'),
('Themes and visual consistency','The application supports light and midnight presentation. Softboard defaults to midnight when entered, while users may switch. Labels intentionally show the currently active theme after the user clarified that preference.','The board uses CSS gradients/textures and subtle shadow rather than external image assets. Light mode has an intentionally warm companion treatment.','Explain that visual design affects usability. Keep this answer practical; accessibility contrast and reduced-motion preference are future improvements to mention.'),
('Server validation and error design','Treat every incoming value as untrusted. Validate required fields, enums, sizes, file MIME/type, ObjectId format and permission before database/action side effects.','express-validator and matched data are used with centralized error responses. Client messages avoid exposing internals such as raw stack traces.','Validation is also a product feature: specific errors help users recover. Security is layered, not a single middleware package.'),
('Rate limiting and security headers','Rate limits slow repeated abuse; headers give browsers safer defaults. Neither replaces authentication or input validation.','Production limits are 100 requests per IP per 15 minutes (higher in development). Headers include nosniff, DENY framing and no-referrer policy.','Explain that limits need monitoring and tuning. A NAT/shared network can make simple IP limits imperfect; production systems may use user/account signals too.'),
('Secrets and configuration','Secrets are environment configuration, not source code. The API needs database, JWT, SMTP, AWS and allowed-origin values; the front end uses only non-secret build-time values such as public API URL.','Vercel environment variables keep deployment secrets outside Git. Never commit .env files, access keys, database password or SMTP credentials.','If a secret leaks, rotate/revoke it; deleting a repository line is not enough because Git history may retain it.'),
('Secrets, environment variables and GitHub security','A secret is a value that grants access or identity: database URI/password, JWT signing secret, SMTP credential, AWS key, Redis connection URL or API token. It is not hardcoded. The code reads a named environment variable at runtime, while the actual value is stored outside the repository.','Locally, Task Force Orbit loads .env values through dotenv; .env.example documents only safe placeholder names. In Vercel, sensitive values are stored in the API project Environment Variables settings and injected into the serverless function process as process.env. The React frontend never receives backend secrets: only intentionally public build-time configuration can be exposed to the browser. Before every Git push, inspect git status/diff, keep .env ignored, stage explicit source files, and scan for accidental credentials.','An interviewer may ask how the server reads a secret. Answer: the deployment platform injects the value into the server process at runtime; Node reads process.env.REDIS_URL or process.env.MONGO_URI, but neither the source code nor browser bundle contains the value. If a secret leaks, revoke/rotate it at the provider, replace the deployment variable, redeploy, and review Git history/logs. Removing one line is not sufficient.'),
('Testing strategy and honest evidence','Testing covers high-value logic: authentication boundaries, CORS, role permissions, workflow transitions, validation and rate limits. API tests recorded 21 passing checks; frontend build and lint were run.','Be precise: a browser E2E run was configured but the last local run did not complete due to local port/worker conditions. Do not claim it passed.','A strong answer includes what was tested, why those risks were prioritised, and what remains to automate.'),
('Local development workflow','Development uses separate API and Vite client servers. The frontend is configured with the API base URL; CORS admits the local origin; environment files provide local credentials.','A “Failed to fetch” usually means API is not running, wrong base URL, CORS mismatch, expired auth, or network/server error—not automatically a React bug.','Debug from outside in: browser Network tab, API health route/logs, server response, environment values, then database/provider dependency.'),
('Git and release workflow','Git snapshots working code; GitHub is the remote collaboration/history layer. A release-worthy change should be reviewed locally, intentionally staged, committed with a focused message, pushed, and then deployed.','The work used a feature branch and draft PR. Avoid committing security protocols, .env files or unrelated local artifacts.','Explain why small commits matter: easier review, rollback and debugging. Do not present “pushed to GitHub” as automatically “live.”'),
('Secure SDLC and release gates','A secure software-development lifecycle (SDLC) makes security and quality checks part of normal delivery: plan the risk, code on a branch, verify the build, test a safe preview, then monitor the release.','The practical Task Force Orbit routine is intentionally lightweight: inspect the diff for secrets, run relevant API/frontend checks, review the change locally, push a focused commit, deploy, and smoke-test the live routes. Keep the API environment variables only in Vercel, and retain a known-good deployment for rollback.','Do not claim enterprise WAF, SSO, or automated security scanning is configured unless it is. The important interview point is the release discipline: changes are verified before and after deployment, and a failed deployment can be reverted to a known-good version.'),
('Vercel deployment model','Frontend and API are deployed as separate Vercel projects. The custom site domain serves the React app; the API has its own deployment endpoint.','Production environment variables are configured in Vercel. Deployment verification checks key frontend routes, API health and protected-route behaviour.','This is simple operationally. A container/Kubernetes platform would be excessive for a placement-scale Express/Vite project unless requirements demanded it.'),
('Production verification checklist','After deploy, verify the actual domain, not only build success. Test registration/resend, login, project creation, permissions, task submission/review, project brief access, notification and Softboard.','Also verify API health, CORS from the deployed origin, S3 signed access, email delivery/provider response, and that unauthenticated protected APIs return 401.','A deploy is a hypothesis until smoke checks pass. Keep a short change log and revert/rollback plan.'),
('Observability and incident response','Logs, error tracking and metrics turn failures into diagnosable events. Current project checks emphasize route status and application responses; mature production would add structured logs and alerts.','For an email problem: capture provider result, API error, user verification state, token expiry, spam/delivery state and database record—rather than guessing.','Discuss Sentry or similar as a future option, not an implemented feature unless it is actually configured.'),
('Scalability roadmap','Scale only after measuring the bottleneck. Candidates include database indexes, cache for read-heavy dashboards, object lifecycle policies, queue-backed email, and real-time events.','The current architecture is intentionally economical: MongoDB, REST, polling and Vercel. It is appropriate for portfolio traffic and learning goals.','Avoid saying “MongoDB scales infinitely.” Explain workload-dependent scaling and the need for performance measurement.'),
('Alternative: SQL and transactions','PostgreSQL would be compelling for complex reporting, strong relational constraints and multi-record financial-like transactions. MongoDB was selected for iteration speed and document-oriented product data.','If strict cross-document atomicity became critical, use MongoDB sessions/transactions where supported—or reconsider relational modeling.','A good decision answer is conditional: “I chose X for current access patterns; I would select Y if requirements changed.”'),
('Alternative: WebSockets, queues and cache','WebSockets give immediate event delivery; queues make email/retry processing durable; Redis provides fast cache/session/rate-limit primitives.','Task Force Orbit does not require them to satisfy its current portfolio scope. It uses REST responses, persisted notifications and periodic polling.','Mention complexity costs: connection lifecycle, retries/idempotency, infrastructure, monitoring and cache invalidation.'),
('Redis: shared production rate limiting','Redis is an in-memory key-value database designed for fast, temporary and shared data. MongoDB remains the permanent source of truth; Redis holds expiring counters rather than users, tasks or files.','Task Force Orbit uses Upstash Redis only for one shared authentication counter: 30 requests per visitor IP per 15 minutes across registration, login, forgot password, resend verification and reset password. The normal API limit remains 100 requests per IP per 15 minutes. Redis keys use the taskforce:auth-rate-limit prefix and expire with the rate-limit window.','Vercel functions can run in separate instances, so normal process memory is not reliably shared. Redis gives every instance the same counter. We avoided caching project/task data because stale collaboration data would be worse than a small database read at portfolio scale.'),
('Redis connection, TLS and TCP versus HTTP','A Redis client can use the native Redis TCP protocol or a provider REST/HTTP API. This project uses node-redis with rate-limit-redis over TCP protected by TLS; the managed Upstash database is deployed near the Vercel API in AWS US-East.','The server connects Redis before importing the Express app because the rate-limit Redis store initializes at app import time. Upstash displays a redis-cli --tls -u command; the connector safely accepts that copied form or a raw URL, extracts the URL, and normalizes Upstash TCP redis:// to secure rediss:// for node-redis. REDIS_URL lives only in local/Vercel environment variables.','TCP fits the existing rate-limit-redis adapter, which sends Redis commands directly. Upstash REST/HTTP is also valid, especially for fetch-based serverless code, but would require a different Redis client/store integration. Never commit a connection URL: it contains the password.'),
('Alternative: OAuth and managed identity','JWT/password auth gives full learning/control over the flow. OAuth/managed identity can improve user convenience and outsource credential handling, but adds provider configuration and account-linking rules.','The existing system verifies emails, hashes passwords and rotates refresh credentials. Google login would be a sensible future addition.','Never say OAuth means “no security work.” You still validate tokens, redirect URIs, roles and account provisioning.'),
('Cost and safety thinking','Cloud services are useful but not free. S3 costs storage/requests/egress; email services have quotas; Vercel and Atlas have plan limits.','Practical safeguards include small upload limits, private objects, signed links, no public credential exposure and avoiding unnecessary polling or duplicate uploads.','Interviewers like cost awareness. Give principles, not made-up cost numbers; pricing changes by plan and region.'),
('Security threat-model answer','Start with assets: accounts, project data, files and cloud credentials. Threats include credential theft, authorization bypass, malicious uploads, token leakage, abuse and accidental public files.','Controls map to threats: bcrypt/reset hashes, server RBAC, file constraints/private S3, in-memory access token/httpOnly refresh cookie, rate limiting and environment secrets.','Finish with residual risks and roadmap: audit logs, malware scanning, CSP, monitoring, password reset throttling and penetration testing.'),
('Frontend interview question bank','Know: component/state, useEffect dependencies, controlled forms, route guards, optimistic update, rendering keys, loading/error states and accessibility.','Project examples: Softboard optimistic slot move; API helper refresh/retry; modal errors; themed UI; five-minute refetch.','Answer structure: definition → project example → trade-off. Example question: “Why not global state?” Answer: local/component state was sufficient; add Context/Zustand/Redux only when cross-tree shared complexity justifies it.'),
('Backend interview question bank','Know: middleware order, async error handling, HTTP semantics, idempotency, validation, pagination, authentication vs authorization and rate limiting.','Project examples: verifyJWT before project permission; validated file upload; controlled task transitions; consistent response formats.','Example question: “What if two people update a task?” Answer: current product uses server validation and last successful update behavior; robust future options include version fields/optimistic concurrency and audit history.'),
('Database interview question bank','Know: documents/collections, schema validation, indexes, references, consistency, aggregation, pagination and N+1 query awareness.','Project examples: independent users/projects/memberships/tasks; S3 metadata in Mongo; unique constraints; role lookups.','Example question: “Why not store files in Mongo?” Answer: object storage is designed for binary objects and signed access; database keeps searchable metadata and relationships.'),
('Behavioral ownership answers','Use STAR: Situation, Task, Action, Result. Pick real examples: duplicate project error UX, unverified re-registration, review-state correction, attachment duplication cleanup, or Softboard drag performance redesign.','State what you observed, the root cause you verified, the minimal fix, how you tested it, and what you learned.','Do not claim a metric you never measured. “It made the UI immediately responsive in manual testing” is credible; invented percentages are not.'),
('Interview demo plan','For a five-minute demo: one sentence problem, login, dashboard, create/open project, show roles and workflow, upload/view brief, task review, notifications, Softboard, then architecture summary.','Prepare a stable demo account/data and a backup screen recording. Keep cloud credentials off screen.','Narrate decisions while clicking. An interviewer needs to see intent, not every page.'),
('What to say when you do not know','Use intellectual honesty: “I have not implemented that yet. My current design does X because Y. To address your concern I would evaluate A and B, then test impact on Z.”','Examples: WebSockets, malware scanning, observability stack, database transactions, multi-device softboard conflict resolution.','This is stronger than guessing. Interviewers often test reasoning beyond the implemented scope.'),
('One-page mental map before interview','Remember the chain: user → React/Vite → API helper → Express middleware → JWT/RBAC → controller/validation → Mongoose/MongoDB → S3/SMTP → response/notification → Vercel deploy.','For every layer, know one benefit, one risk and one future upgrade. Practise saying it in order without notes.','Your goal is a coherent engineering story: user problem, safe implementation, verification, trade-off and next iteration.'),
]

def shade(cell, fill):
    tcPr = cell._tc.get_or_add_tcPr(); shd=OxmlElement('w:shd'); shd.set(qn('w:fill'),fill); tcPr.append(shd)
def font(run,size=11,bold=False,color=INK,italic=False):
    run.font.name='Calibri'; run._element.rPr.rFonts.set(qn('w:ascii'),'Calibri'); run._element.rPr.rFonts.set(qn('w:hAnsi'),'Calibri'); run.font.size=Pt(size); run.bold=bold; run.italic=italic; run.font.color.rgb=RGBColor.from_string(color)
def p(doc,text='',style=None,after=6,before=0,align=None):
    x=doc.add_paragraph(style=style); x.paragraph_format.space_after=Pt(after); x.paragraph_format.space_before=Pt(before); x.paragraph_format.line_spacing=1.16
    if align: x.alignment=align
    r=x.add_run(text); font(r); return x
def bullet(doc,text):
    x=doc.add_paragraph(style='List Bullet'); x.paragraph_format.space_after=Pt(4); x.paragraph_format.line_spacing=1.12; font(x.add_run(text),10.5); return x
def set_cell(cell,text,bold=False,fill=None):
    if fill: shade(cell,fill)
    cell.vertical_alignment=WD_CELL_VERTICAL_ALIGNMENT.CENTER
    para=cell.paragraphs[0]; para.paragraph_format.space_after=Pt(2); para.paragraph_format.space_before=Pt(2)
    font(para.add_run(text),9.5,bold, 'FFFFFF' if fill==NAVY else INK)
def table(doc, rows):
    t=doc.add_table(rows=len(rows), cols=2); t.autofit=False; t.alignment=WD_TABLE_ALIGNMENT.LEFT
    widths=[Inches(1.48), Inches(4.92)]
    for row,vals in zip(t.rows,rows):
        for c,w,v in zip(row.cells,widths,vals): c.width=w; set_cell(c,v, bold=(c==row.cells[0]), fill=(PALE if c==row.cells[0] else None))
    p(doc,'',after=2); return t
def code_block(doc,text):
    t=doc.add_table(rows=1, cols=1); t.autofit=False; t.alignment=WD_TABLE_ALIGNMENT.LEFT
    cell=t.cell(0,0); shade(cell,'EEF2F6'); cell.vertical_alignment=WD_CELL_VERTICAL_ALIGNMENT.CENTER
    para=cell.paragraphs[0]; para.paragraph_format.space_after=Pt(5); para.paragraph_format.space_before=Pt(5)
    run=para.add_run(text); run.font.name='Consolas'; run._element.rPr.rFonts.set(qn('w:ascii'),'Consolas'); run._element.rPr.rFonts.set(qn('w:hAnsi'),'Consolas'); run.font.size=Pt(8.5); run.font.color.rgb=RGBColor.from_string(INK)
    p(doc,'',after=3)

doc=Document(); sec=doc.sections[0]; sec.top_margin=Inches(.78); sec.bottom_margin=Inches(.72); sec.left_margin=Inches(.82); sec.right_margin=Inches(.82); sec.header_distance=Inches(.35); sec.footer_distance=Inches(.35)
styles=doc.styles
styles['Normal'].font.name='Calibri'; styles['Normal'].font.size=Pt(11); styles['Normal']._element.rPr.rFonts.set(qn('w:ascii'),'Calibri'); styles['Normal']._element.rPr.rFonts.set(qn('w:hAnsi'),'Calibri')
for name,size,color,before,after in [('Heading 1',17,BLUE,12,7),('Heading 2',13,NAVY,8,4),('Heading 3',11,NAVY,6,3)]:
    st=styles[name]; st.font.name='Calibri'; st.font.size=Pt(size); st.font.bold=True; st.font.color.rgb=RGBColor.from_string(color); st._element.rPr.rFonts.set(qn('w:ascii'),'Calibri'); st._element.rPr.rFonts.set(qn('w:hAnsi'),'Calibri'); st.paragraph_format.space_before=Pt(before); st.paragraph_format.space_after=Pt(after)
header=sec.header.paragraphs[0]; header.alignment=WD_ALIGN_PARAGRAPH.RIGHT; font(header.add_run('TASK FORCE ORBIT  |  PLACEMENT HANDBOOK'),8.5,True,'61758B')
footer=sec.footer.paragraphs[0]; footer.alignment=WD_ALIGN_PARAGRAPH.CENTER; font(footer.add_run('Task Force Orbit • Placement preparation • Page '),8,False,'61758B'); fld=OxmlElement('w:fldSimple'); fld.set(qn('w:instr'),'PAGE'); footer._p.append(fld)

p(doc,'TASK FORCE ORBIT',after=10,before=100,align=WD_ALIGN_PARAGRAPH.CENTER).runs[0].font.color.rgb=RGBColor.from_string(BLUE); doc.paragraphs[-1].runs[0].font.size=Pt(15); doc.paragraphs[-1].runs[0].bold=True
title=p(doc,'Complete Placement Interview Handbook',after=10,align=WD_ALIGN_PARAGRAPH.CENTER); title.runs[0].font.size=Pt(28); title.runs[0].font.color.rgb=RGBColor.from_string(NAVY); title.runs[0].bold=True
sub=p(doc,'A broad, honest technical guide to the architecture, implementation choices, interview questions and production thinking behind your final-year B.Tech project.',after=22,align=WD_ALIGN_PARAGRAPH.CENTER); sub.runs[0].italic=True; sub.runs[0].font.color.rgb=RGBColor.from_string('4E647A')
table(doc,[('Purpose','Build interview-ready understanding, not memorised buzzwords.'),('How to revise','Read the pitch and mental map first; then take one chapter per study session.'),('Evidence rule','Separate implemented features, verified tests and future improvements.'),('Version','Prepared for Task Force Orbit placement preparation • August 2026')])
p(doc,'How to use this document',style='Heading 2'); bullet(doc,'Answer in layers: definition → Task Force Orbit example → trade-off → next improvement.'); bullet(doc,'Never invent metrics, security guarantees or passing tests. Honest scope is a strength.'); bullet(doc,'Use the source list for concepts, but describe your own implementation in your own words.')

for n,(title,idea,implementation,tradeoff) in enumerate(topics,1):
    doc.add_page_break(); p(doc,f'CHAPTER {n:02d}',after=2).runs[0].font.color.rgb=RGBColor.from_string('6D8296'); doc.paragraphs[-1].runs[0].font.size=Pt(9); doc.paragraphs[-1].runs[0].bold=True
    h=p(doc,title,style='Heading 1');
    p(doc,'Essential idea',style='Heading 2'); p(doc,idea,after=8)
    table(doc,[('Task Force Orbit',implementation),('Decision / trade-off',tradeoff)])
    p(doc,'Interview-ready answer',style='Heading 2')
    p(doc,f'“{idea} In Task Force Orbit, {implementation.lower()} The key trade-off is that {tradeoff.lower()}”',after=8)
    p(doc,'Likely follow-up questions',style='Heading 2')
    bullet(doc,f'What problem does this solve, and what would fail without it?')
    bullet(doc,f'Why was this choice appropriate for a final-year, production-minded project rather than the most complex possible design?')
    bullet(doc,f'What is one limitation today, and how would you validate the next upgrade?')
    p(doc,'Memory anchor',style='Heading 2'); p(doc, f'{title}: problem → implementation → control → trade-off → next step.',after=3)

doc.add_page_break(); p(doc,'APPENDIX A — 15 rapid-fire questions',style='Heading 1')
rapid=[('Authentication vs authorization','Authentication proves identity; authorization decides permitted action.'),('Why refresh tokens?','They renew short-lived access without asking for password repeatedly.'),('Why httpOnly cookie?','JavaScript cannot read it, reducing token theft through XSS.'),('Why private S3?','Files should not become public merely because someone guesses a URL.'),('Why signed URL?','It grants short-lived, specific object access after API authorization.'),('Why rate limit?','To slow abuse and protect service capacity.'),('Why database constraint?','It remains correct even with concurrent application requests.'),('Why validation twice?','Client for user experience; server for trust boundary.'),('Why role check server-side?','UI can be bypassed; server owns the protected data.'),('Why MongoDB?','Document-oriented iteration matched current product access patterns.'),('Why not WebSockets yet?','Polling met freshness needs with simpler operation.'),('What is optimistic UI?','Show local result immediately, then reconcile/persist server result.'),('What does CORS do?','Browser-origin policy; it is not an identity mechanism.'),('What is idempotency?','Repeating an operation produces the same intended final effect.'),('What is your proud design choice?','Controlled review states plus role checks make collaboration rules explicit.')]
for q,a in rapid: p(doc,q,style='Heading 3'); p(doc,a,after=5)
doc.add_page_break(); p(doc,'APPENDIX B — Interviewer expectations and answer checklist',style='Heading 1')
for item in ['State the business problem before the technology.','Name the boundary: browser, API, database, cloud object store or email provider.','Give one exact code-level/project example.','Name a trade-off and why it was acceptable.','Say how you verified it.','Name one realistic future improvement without pretending it already exists.','Keep sensitive values and private credentials out of demonstration screens.']:
    bullet(doc,item)
p(doc,'Research sources',style='Heading 2')
for s in ['OWASP Authentication Cheat Sheet — https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html','OWASP Session Management Cheat Sheet — https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html','OWASP REST Security Cheat Sheet — https://cheatsheetseries.owasp.org/cheatsheets/REST_Security_Cheat_Sheet.html','MDN CORS Guide — https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/CORS','MongoDB: Embed versus References — https://www.mongodb.com/docs/v7.2/data-modeling/concepts/embedding-vs-references/','AWS: Presigned URLs — https://docs.aws.amazon.com/AmazonS3/latest/userguide/using-presigned-url.html','Vercel: Secure every step of a modern SDLC — https://assets.vercel.com/image/upload/v1745532177/front/security/Secured_modern_SDLC.pdf','Indeed: Entry-level software engineer interview questions — https://www.indeed.com/career-advice/interviewing/entry-level-software-engineer-interview-questions']:
    p(doc,s,after=4)
doc.add_page_break(); p(doc,'APPENDIX C — MongoDB and Mongoose query brain map',style='Heading 1')
p(doc,'MongoDB stores documents; Mongoose is the Node.js layer that gives those documents schemas, models and query methods. A Task model maps JavaScript calls to the MongoDB task collection.',after=5)
p(doc,'1. Board query: filter, then sort',style='Heading 2')
p(doc,'find() returns matching documents; sort() orders the project board newest first.',after=3)
p(doc,'Before indexing — application query',style='Heading 3')
code_block(doc,'Task.find({ project: projectId })\n  .populate("assignedTo", "avatar username fullName")\n  .sort({ createdAt: -1 });')
p(doc,'Before the matching index exists, MongoDB may use a COLLSCAN (collection scan) and then a separate sort. The JavaScript query is correct, but it has more work as the collection grows.',after=3)
p(doc,'After indexing — same application query, faster database plan',style='Heading 3')
code_block(doc,'Task.find({ project: projectId })\n  .populate("assignedTo", "avatar username fullName")\n  .sort({ createdAt: -1 });\n\n// MongoDB uses: IXSCAN on project_1_createdAt_-1')
p(doc,'The query code does not change. taskSchema.index({ project: 1, createdAt: -1 }) gives MongoDB an ordered path for the filter and sort. IXSCAN means “index scan.”',after=3)
p(doc,'2. Personal deadline query: ObjectId equality plus date range',style='Heading 2')
p(doc,'$gte means “greater than or equal to”; $lt means “less than.”',after=3)
code_block(doc,'Task.find({\n  assignedTo: userId,\n  dueDate: { $gte: startOfToday, $lt: startOfTomorrow }\n}).sort({ dueDate: 1 });')
p(doc,'3. Notification feed: one recipient, newest first',style='Heading 2')
code_block(doc,'Notification.find({ recipient: userId })\n  .sort({ createdAt: -1 });')
p(doc,'4. What an index changes',style='Heading 2')
p(doc,'An index is a smaller ordered lookup structure. This one matches “recipient, then newest first,” so MongoDB can locate and order a user’s feed more efficiently.',after=3)
code_block(doc,'notificationSchema.index({ recipient: 1, createdAt: -1 });')
doc.add_page_break(); p(doc,'5. Index verification and trade-offs',style='Heading 2')
p(doc,'Brain map: schema describes data → model exposes methods → Mongoose sends the query → MongoDB query planner selects an execution plan → the selected index narrows and orders the search.',after=5)
p(doc,'I verified the added indexes with explain(), a read-only query-plan inspection. It shows whether MongoDB selects IXSCAN or falls back to COLLSCAN.',after=3)
code_block(doc,'await Task.find({ project: projectId })\n  .sort({ createdAt: -1 })\n  .explain("queryPlanner");')
p(doc,'Current indexes: User email/username, unique project name, unique project-invite { project, email }, Softboard owner, Task { project, createdAt }, Task { assignedTo, dueDate }, Notification { recipient, createdAt }, Activity { project, createdAt }, and unique ProjectMember { project, user }. The five query indexes were verified with explain(): MongoDB selected project_1_createdAt_-1, assignedTo_1_dueDate_1, recipient_1_createdAt_-1, and project_1_user_1. Indexes consume storage and add write work, so they should match real query patterns.',after=4)
p(doc,'Interview answer',style='Heading 2')
p(doc,'“Mongoose builds my query, while MongoDB executes it. Task.find filters board tasks by project and sort orders them by creation time. I kept the same query and added a compound { project, createdAt } index, so MongoDB can choose an IXSCAN rather than scanning and separately sorting a growing collection. I add indexes only for frequent query patterns because they speed reads but add storage and write overhead.”',after=4)
OUT.parent.mkdir(parents=True,exist_ok=True); doc.save(OUT); print(OUT)
